### ISSUE TITLE
request for data

### ISSUE THREAD

**Issue by loveforeverLi** [i2Nav-WHU/Wheel-SLAM#1]
Thanks for sharing this amazing work, can you please provide the dataset for test?

**Comment by YibinWu** [comment]
Hi, thanks for your interest in our work. We released a set of test data with ground truth. Please see the [data folder](https://github.com/i2Nav-WHU/Wheel-SLAM/tree/main/data) of this repo.

**Comment by YibinWu** [comment]
> Hi, thanks for your interest in our work. We released a set of test data with ground truth. Please see the [data folder](https://github.com/i2Nav-WHU/Wheel-SLAM/tree/main/data) of this repo.

Hi, thanks for your interest in our work. We released a set of test data with ground truth. Please see the [data folder](https://github.com/i2Nav-WHU/Wheel-SLAM/tree/main/data) of this repo.

**Comment by YibinWu** [comment]
> Thanks for sharing this amazing work, can you please provide the dataset for test?

Hi, thanks for your interest in our work. We released a set of test data with ground truth. Please see the [data folder](https://github.com/i2Nav-WHU/Wheel-SLAM/tree/main/data) of this repo.
