### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by wdh234** [i2Nav-WHU/Wheel-SLAM#2]
******Wheel SLAM RUNNING:99.9%******
Reference & Wheel-INS Time Error!
出错 ResCompare (line 5)
    wheelins  = wheelinsDR;

调用 "E:\matlab_test\Wheel-SLAM-main\Wheel-SLAM-main\utils\ResCompare.m>ResCompare" 时，未对输出参数 "err1" (可能还包括其他参数)赋值。

出错 wheelslam_func (line 228)
[~, wheelslam_rms, ~, wheelins_rms, ~, ~] =...

出错 wheelslam_main (line 11)
    [result(i,1:2), result(i,3:4)]= wheelslam_func(paras);

matlab2014 运行报这样的错误，请问怎么解决呢？

**Comment by 15707397862** [comment]
******Wheel SLAM RUNNING:99.9%******
Reference & Wheel-INS Time Error!
调用 "ResCompare" 时，未对输出参数 "err1" (可能还包括其他参数)赋值。

出错 wheelslam_func (第 229 行)
    ResCompare(res, particleres, wheelinsDR, gt_path, freq);

出错 wheelslam_main (第 11 行)
    [result(i,1:2), result(i,3:4)]= wheelslam_func(paras);



matlab2020报错

**Comment by YibinWu** [comment]
Hi, thanks for your interest in our work. This issue is due to the format error of the ground truth data. Now we have fixed it. Please try the new [ground truth data](https://github.com/i2Nav-WHU/Wheel-SLAM/blob/main/data/ground_truth.bin) in the repo.

**Comment by YibinWu** [comment]
> ******Wheel SLAM RUNNING:99.9%****** Reference & Wheel-INS Time Error! 调用 "ResCompare" 时，未对输出参数 "err1" (可能还包括其他参数)赋值。
> 
> 出错 wheelslam_func (第 229 行) ResCompare(res, particleres, wheelinsDR, gt_path, freq);
> 
> 出错 wheelslam_main (第 11 行) [result(i,1:2), result(i,3:4)]= wheelslam_func(paras);
> 
> matlab2020报错

Hi, thanks for your interest in our work. This issue is due to the format error of the ground truth data. Now we have fixed it. Please try the new [ground truth data](https://github.com/i2Nav-WHU/Wheel-SLAM/blob/main/data/ground_truth.bin) in the repo.

**Comment by YibinWu** [comment]
> ******Wheel SLAM RUNNING:99.9%****** Reference & Wheel-INS Time Error! 调用 "ResCompare" 时，未对输出参数 "err1" (可能还包括其他参数)赋值。
> 
> 出错 wheelslam_func (第 229 行) ResCompare(res, particleres, wheelinsDR, gt_path, freq);
> 
> 出错 wheelslam_main (第 11 行) [result(i,1:2), result(i,3:4)]= wheelslam_func(paras);
> 
> matlab2020报错

Hi, thanks for your interest in our work. This issue is due to the format error of the ground truth data. Now we have fixed it. Please try the new [ground truth data](https://github.com/i2Nav-WHU/Wheel-SLAM/blob/main/data/ground_truth.bin) in the repo.
