### ISSUE TITLE
什么时候能开源基于C++的代码呢？

### ISSUE THREAD

**Issue by xyckong** [i2Nav-WHU/Wheel-SLAM#3]

**Comment by YibinWu** [comment]
您好，感谢您对我们工作的兴趣。很抱歉我们暂时没有足够的时间和精力来实现C++代码，但是我们欢迎感兴趣的同学与我们合作开发C++/python版本，我们也愿意提供相应的帮助。

**Comment by YibinWu** [comment]
> _No description provided._

您好，感谢您对我们工作的兴趣。很抱歉我们暂时没有足够的时间和精力来实现C++代码，但是我们欢迎感兴趣的同学与我们合作开发C++/python版本，我们也愿意提供相应的帮助。
